project:
  type: website
  output-dir: docs

website:
  title: "William Reddien"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        href: index.qmd
      - text: "On Cataloging and Displays"
        href: catalogs.qmd
      - text: "My Dataset"
        href: mydata.qmd
      - text: "Project Results"
        href: conclusions.qmd
      - text: "Data Analyses and Models"
        menu:
        
        - auctiondata.qmd
        - imageclassifier.qmd
      - about.qmd


format:
  html:
    theme: sandstone
    css: backgroundsettings.css
    toc: true

editor: visual

