---
title: "About"
---

About this site + Me

I am a current undergraduate student at Davidson College in the class of 2029. I'm studying Data science, organization, and analysis, along with Computer Science.

I developed this website while abroad in Germany on Davidson College's Dean Rusk travel Grant as part of my project studying the eagle as it appears on ancient coins. This website houses all of the other projects, programs, databases, and evaluations I wrote/developed while abroad as part of my project, and serves as a digital portfolio whose development helped me learn and increase proficiency in many data science skills (and whose existence stands as a testament to those skills).

I am a proficient SQL and R programmer, and am likewise skilled not only in base Python but the pandas library. I have experience with most fundamental tools in Excel, and am currently actively expanding that facet of my knowledge.

Previously, I've worked as an intern in two positions— as a lab intern at MIT I used R to visually create and analyze data drawn from cellular activity, and as a market research intern with a Texas law firm I evaluated potential clients as well as strategized the most effective ways to begin building relationships with them.

As a member of the "Cats' Stats" club at Davidson, I've spent a substantial amount of time analyzing the data surrounding not only Davidson's basketball team but our opponents, building scouting reports on strengths and weaknesses of teams and players, and prescribing strategies that lead our team to victory.

When I'm not working, programming, learning a new skill, or looking at coins, I spend most of my time running, playing and designing video games, reading, writing, watching movies, and spending time with my friends.

If you have any questions about the site, my projects, or myself, email me at:

w.reddien\@outlook.com

Or, connect/reach out to me via LinkedIn here:

<https://www.linkedin.com/in/william-reddien-6726473a9/>
