---
title: "Conclusions"
#format: html
---

## The Success of the Project

Ultimately this project was a raging success. Out of the goals I set out to achieve (as listed on the main webpage) I have completed them all, with the launch of this website marking the final goal complete. Throughout this experience I was able to explore not only large museums but local shops while I built my own cross-collection comprehensive dataset of ancient eagle coins.

Through my own research and work documenting coins, as well as investigating large collections, I was able to gain a substantial understanding of the variations in coin cataloging both online and in a physical presentation. In the 'Data Analyses and Models' section of this site, you can experiment with and see how I both developed a linear regression price prediction model for ancient coins, and trained an image classification model to identify the presence of eagles on coins.

And finally, this website, which showcases not only the projects I developed, but everything I learned along the way.

As the project comes to a close I am becoming increasingly happy with the work that I've done, and I am incredibly thankful to have been given the opportunity to pursue this passion project.

## My (brief) Discussion with a Curator

When I originally set out to complete this project, I had grand hopes of meeting with curators or collection managers, studying in studiensaals, and learning about where every coin each collection comes from through discussions with figureheads. Unfortunately, though I reached out to a number of institutions (and ultimately visited many of them), I did not receive a single reply, even upon following up. While I am generally disappointed with this, I was still able to achieve almost all of what I set out to do, and as such the detail seems minute.

However, I did have one chance to talk for only a few minutes with a curator of the Staatliche Muenzsammlung in Munich. After spending quite a bit of time in the collection I realized that it was almost its closing time. I was leaving, but fortunately as I was walking towards the door, I ran into a man I didn't catch the name of, but who I was told by the desk attendant was one of the experts on the museum. I spoke to him briefly in German, and was thankfully able to ask him a handful of questions I had prepared in advance just in case this happened.

Through our very brief discussion, I was able to learn a number of things about Munich's collection. Firstly, they do actively purchase coins even to this day, despite the collection being over 500 years old. This was also notable, since the curator mentioned that buying coins was their primary way of acquiring new artifacts (as opposed to donations or from archaeological excavations). The museum has a digital catalog (which I had already engaged with), and it is updated to include all new acquisitions. While I speak and read German relatively effectively, I couldn't determine what some of the displays were, in particular several giant, ornate cases. The curator explained to me that they were the boxes in which the coins had been stored leading up to the modern day, hence the existence of the collection for 500 years.

We talked a bit more briefly about the collection, but only a bit longer since he seemed to be busy. I had learned what I needed, though, since purchased coins (as you might expect, and as I learned through creating my auctiondata dataset) are highly documented, and thus, combined with their digital catalog, seems to be extensively and observably documented, in such a way that I am able to learn a great deal about their documentation style by engaging with their digital system.

## Into the Future

I briefly touched on future goals for this project in other website pages, but as the project comes to a close all I can think about are more ideas to add to it. I spent quite honestly too much time while working on this project trying to find or make a complete dataset of the \~36,000 eagle coins *MANTIS* features in their database, so that I could develop more resources with it. While that goal has been paused for the sake of time management, that dataset would be the first thing I create in a continuation of this project. Thankfully, after learning and experimenting with Python's pandas, I have the tools necessary to (if very tediously) build this dataset myself.

Along with that dataset, I would like to create an interactive map, such that as a user changes a date input eagle coins from around that time period begin to appear and disappear, creating a visual of where eagle coins were being minted and when.

I would also love to expand the scope of certain parts of this project beyond just ancient eagle coins, to include coins of different time periods or non-eagalic ancient coins. While I find eagle coins in particular to be very fascinating, my universal dataset would be much more applicable if it featured a comprehensive database of all classical coins, and not just those with eagles.

As mentioned on my image classification model page, I would love to keep training it as well, potentially building my training dataset such that it can identify eagle coins of different eras, different materials, or different locations.

Even beyond what I've just mentioned there is so much more to be added, and while this project has been limited in both timeframe and scope, a future iteration would be an incredibly exciting project to lead. With the infrastructure now laid out, the project could be expanded through more of Europe, including collections from cities much closer to the heart of Rome, with so much more valuable information being included. One day if this project continues to grow, it could change the way modern numismatics operates and expedite our understanding of the ancient world.
